### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by apu52**
Hello Sir, 
I have added some API stat small boxes that will help you to track some notifications like
- visitors count
- GitHub forks
- GitHub Repo stars
- GitHub contributors

### CODE REVIEW

**Comment by apu52** [comment]
@Harold-lkk  @ZwwWayne  Please review my changes & please merge it.

**Comment by Harold-lkk** [comment]
Would please add 
- visitors count
- GitHub forks
- GitHub Repo stars
- GitHub contributors

in others readme.md ?

**Comment by apu52** [comment]
> Would please add
> 
> * visitors count
> * GitHub forks
> * GitHub Repo stars
> * GitHub contributors
> 
> in others readme.md ?

I WANT TO ADD THIS TO  THIS README.MD .IT WILL HELP YOU

**Comment by apu52** [comment]
@Harold-lkk @ZwwWayne Please review my changes & please merge it.

**Comment by apu52** [comment]
@Harold-lkk @ZwwWayne Please review my changes & please merge it.
Sir, Please merge it...it's a request

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
